<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sso/v1/api.proto

namespace GPBMetadata\Sso\V1;

class Api
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Sso\V1\IdentityProvider::initOnce();
        \GPBMetadata\Sso\V1\ServiceProvider::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af4030a1073736f2f76312f6170692e70726f746f120673736f2e76311a" .
            "1e73736f2f76312f6964656e746974795f70726f76696465722e70726f74" .
            "6f1a1d73736f2f76312f736572766963655f70726f76696465722e70726f" .
            "746f32f9010a104964656e7469747950726f766964657212480a0b476574" .
            "456e74727955524c121a2e73736f2e76312e476574456e74727955524c52" .
            "6571756573741a1b2e73736f2e76312e476574456e74727955524c526573" .
            "706f6e7365220012600a13476574456e74727955524c57697468436f6465" .
            "12222e73736f2e76312e476574456e74727955524c57697468436f646552" .
            "6571756573741a232e73736f2e76312e476574456e74727955524c576974" .
            "68436f6465526573706f6e7365220012390a064c6f676f757412152e7373" .
            "6f2e76312e4c6f676f7574526571756573741a162e676f6f676c652e7072" .
            "6f746f6275662e456d707479220032790a0f5365727669636550726f7669" .
            "64657212660a1547657453657373696f6e5472616e7366657255524c1224" .
            "2e73736f2e76312e47657453657373696f6e5472616e7366657255524c52" .
            "6571756573741a252e73736f2e76312e47657453657373696f6e5472616e" .
            "7366657255524c526573706f6e73652200421a0a13636f6d2e76656e6461" .
            "7374612e73736f2e7631420353534f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

