<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sso/v1/identity_provider.proto

namespace Sso\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>sso.v1.GetEntryURLResponse</code>
 */
class GetEntryURLResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The entry URL
     * </pre>
     *
     * <code>string entry_url = 1;</code>
     */
    private $entry_url = '';

    public function __construct() {
        \GPBMetadata\Sso\V1\IdentityProvider::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The entry URL
     * </pre>
     *
     * <code>string entry_url = 1;</code>
     */
    public function getEntryUrl()
    {
        return $this->entry_url;
    }

    /**
     * <pre>
     * The entry URL
     * </pre>
     *
     * <code>string entry_url = 1;</code>
     */
    public function setEntryUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->entry_url = $var;
    }

}

