<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sso/v1/identity_provider.proto

namespace Sso\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>sso.v1.GetEntryURLRequest</code>
 */
class GetEntryURLRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The service provider ID.
     * </pre>
     *
     * <code>string service_provider_id = 1;</code>
     */
    private $service_provider_id = '';
    /**
     * <pre>
     * See ServiceContext for more information.
     * </pre>
     *
     * <code>.sso.v1.ServiceContext context = 2;</code>
     */
    private $context = null;

    public function __construct() {
        \GPBMetadata\Sso\V1\IdentityProvider::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The service provider ID.
     * </pre>
     *
     * <code>string service_provider_id = 1;</code>
     */
    public function getServiceProviderId()
    {
        return $this->service_provider_id;
    }

    /**
     * <pre>
     * The service provider ID.
     * </pre>
     *
     * <code>string service_provider_id = 1;</code>
     */
    public function setServiceProviderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_provider_id = $var;
    }

    /**
     * <pre>
     * See ServiceContext for more information.
     * </pre>
     *
     * <code>.sso.v1.ServiceContext context = 2;</code>
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * <pre>
     * See ServiceContext for more information.
     * </pre>
     *
     * <code>.sso.v1.ServiceContext context = 2;</code>
     */
    public function setContext(&$var)
    {
        GPBUtil::checkMessage($var, \Sso\V1\ServiceContext::class);
        $this->context = $var;
    }

}

