<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sso/v1/service_provider.proto

namespace Sso\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>sso.v1.ServiceContext.Account</code>
 */
class ServiceContext_Account extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string account_id = 1;</code>
     */
    private $account_id = '';

    public function __construct() {
        \GPBMetadata\Sso\V1\ServiceProvider::initOnce();
        parent::__construct();
    }

    /**
     * <code>string account_id = 1;</code>
     */
    public function getAccountId()
    {
        return $this->account_id;
    }

    /**
     * <code>string account_id = 1;</code>
     */
    public function setAccountId($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_id = $var;
    }

}

