<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sso/v1/service_provider.proto

namespace Sso\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>sso.v1.ServiceContext.SuperAdmin</code>
 */
class ServiceContext_SuperAdmin extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Sso\V1\ServiceProvider::initOnce();
        parent::__construct();
    }

}

